# Generated by Django 3.2.4 on 2022-06-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220601_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.profile'),
        ),
    ]
