# Generated by Django 3.2.4 on 2022-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pet_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='daycares',
            field=models.ManyToManyField(related_name='pets', to='core.Daycare'),
        ),
    ]
