# Generated by Django 3.2.4 on 2022-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220621_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
