# Generated by Django 3.2.4 on 2022-06-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_daycare_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='is_vin',
        ),
    ]
