# Generated by Django 3.2.4 on 2022-06-22 03:27

import PetDays.core.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_postphoto_is_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=PetDays.core.image_helpers.images_filename_generator),
        ),
    ]
