# Generated by Django 3.2.4 on 2022-06-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='daycare',
        ),
    ]
