# Generated by Django 3.2.4 on 2022-06-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pets',
            field=models.ManyToManyField(blank=True, to='core.Pet'),
        ),
    ]
