# Generated by Django 3.2.4 on 2022-06-22 05:29

import PetDays.core.image_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_postphoto_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycare',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=PetDays.core.image_helpers.images_filename_generator),
        ),
    ]
